const PET_IMAGES = {
  'Bat Dragon': 'pets/pet-01.png',
  'Balloon Unicorn': 'pets/pet-02.png',
  'Shadow Dragon': 'pets/pet-04.png',
  'Giant Panda': 'pets/pet-05.png',
  'Nessie': 'pets/pet-06.png',
  'Giraffe': 'pets/pet-07.png',
  'Diamond Butterfly': 'pets/pet-08.png',
  'African Wild Dog': 'pets/pet-09.png',
  'Hedgehog': 'pets/pet-10.png',
  'Frost Dragon': 'pets/pet-11.png',
  'Owl': 'pets/pet-12.png',
  'Cryptid': 'pets/pet-13.png',
  'Dalmatian': 'pets/pet-14.png',
  'Crow': 'pets/pet-15.png',
  'Parrot': 'pets/pet-16.png',
  'Orchid Butterfly': 'pets/pet-17.png',
  'Blazing Lion': 'pets/pet-18.png',
  'Sugar Glider': 'pets/pet-19.png',
  'Kangaroo': 'pets/pet-20.png',
  'Turtle': 'pets/pet-21.png',
  'Cow': 'pets/pet-22.png',
  'Border Collie': 'pets/pet-24.png',
  'Shark Puppy': 'pets/pet-25.png',
  'Meerkat': 'pets/pet-26.png',
  'Haetae': 'pets/pet-27.png',
  'Evil Unicorn': 'pets/pet-28.png',
  'Tio De Nadal': 'pets/tio-de-nadal.png',
  'Aestus': 'pets/aestus.png',
  'Solaris': 'pets/solaris.png',
  'Tri-horned Treehopper': 'pets/tri-horned-treehopper.png',
  'Burger Bear': 'pets/burger-bear.png',
  'Ranger Beaver': 'pets/ranger-beaver.png',
  'Mr. Whiskerpips': 'pets/mr-whiskerpips.png',
  'Mrs. Whiskerpips': 'pets/mrs-whiskerpips.png',
  'Bird of Paradise': 'pets/bird-of-paradise.png',
  'Black Dog': 'pets/black-dog.png',
  'Oakee Wizard': 'pets/oakee-wizard.png',
  'Tealwood Monster': 'pets/tealwood-monster.png',
  'Rainbow Trout': 'pets/rainbow-trout.png',
  'Stygian Owl': 'pets/stygian-owl.png',
  'Storm Condor': 'pets/storm-condor.png',
  'River Otter': 'pets/river-otter.png',
  'Bison': 'pets/bison.png',
  'Nurse Shark': 'pets/nurse-shark.png',
  'Oakee Knight': 'pets/oakee-knight.png',
  'Oakee': 'pets/oakee.png',
  'Irish Setter': 'pets/irish-setter.png',
  'Red Panda Ducky': 'pets/red-panda-ducky.png',
  'Clubtail Dragonfly': 'pets/clubtail-dragonfly.png',
  'Sheepdog Ducky': 'pets/sheepdog-ducky.png',
  'Pilot Gull': 'pets/pilot-gull.png',
  'Gecko Ducky': 'pets/gecko-ducky.png',
  'Safari Egg': 'pets/safari-egg.png',
  'Jungle Egg': 'pets/jungle-egg.png',
  'Farm Egg': 'pets/farm-egg.png',
  'Blue Egg': 'pets/blue-egg.png',
  'Pink Egg': 'pets/pink-egg.png',
  'Christmas Egg': 'pets/christmas-egg.png',
  'Aussie Egg': 'pets/aussie-egg.png',
  'Easter 2020 Egg': 'pets/easter-2020-egg.png',
};

const PETS_ORDER = [
  'Bat Dragon',
  'Shadow Dragon',
  'Giraffe',
  'Frost Dragon',
  'Owl',
  'Parrot',
  'Safari Egg',
  'Crow',
  'Balloon Unicorn',
  'Giant Panda',
  'African Wild Dog',
  'Cryptid',
  'Haetae',
  'Orchid Butterfly',
  'Evil Unicorn',
  'Blazing Lion',
  'Jungle Egg',
  'Farm Egg',
  'Hedgehog',
  'Diamond Butterfly',
  'Dalmatian',
  'Jekyll Hydra',
  'Arctic Reindeer',
  'Blue Egg',
  'Undead Jousting Horse',
  'Mini Pig',
  'Hot Doggo',
  'Goose',
  'Mermicorn',
  'Cow',
  'Pelican',
  'Pink Egg',
  'Strawberry Shortcake Bat Dragon',
  'Chocolate Chip Bat Dragon',
  'Peppermint Penguin',
  'Sugar Glider',
  'Cabbit',
  'Turtle',
  'Monkey King',
  'Werewolf',
  'Siamese Cat',
  'Tortoiseshell Guinea Pig',
  'Flamingo',
  'Christmas Egg',
  'Kangaroo',
  'Candyfloss Chick',
  'Grim Dragon',
  'Caterpillar',
  'Albino Monkey',
  'Elephant',
  'Alpaca',
  'Bush Elephant',
  'Shark Puppy',
  'Lion',
  'Crocodile',
  'Fairy Bat Dragon',
  'Border Collie',
  'Blue Dog',
  'Frost Unicorn',
  'Winged Tiger',
  'Moonbeam Peacock',
  'Candicorn',
  'Emperor Gorilla',
  'Sea Slug',
  'Black-Chested Pheasant',
  'Munchkin Cat',
  'Jellyfish',
  'Royal Mistletroll',
  'Red Dutch Guinea Pig',
  'Vampire Dragon',
  'Irish Water Spaniel',
  'Pig',
  'Lion Cub',
  'Many Mackerel',
  'Tortuga de la Isla',
  'Arctic Fox',
  'Bald Eagle',
  'Goat',
  'Velocirooster',
  'Pink Cat',
  'Tio De Nadal',
  'Pirate Ghost Capuchin Monkey',
  'Cupid Dragon',
  'Giant Anteater',
  'Frostbite Bear',
  'Strawberry Penguin',
  'Mechapup',
  'Phantom Dragon',
  'Sheeeeep',
  'Frost Fury',
  'Sugar Axolotl',
  'Meerkat',
  'Nessie',
  'Owlbear',
  'Aestus',
  'Field Mouse',
  'Solaris',
  'Sakura Spirit',
  'Papa Moose',
  'Ring-Tailed Lemur',
  'Zombie Buffalo',
  'Shrew',
  'Aussie Egg',
  'Happy Clam',
  'Fallow Deer',
  'Brown Bear',
  'Tri-horned Treehopper',
  'Groundhog',
  'Diamond Amazon',
  'Caelum Cervi',
  'Midnight Dragon',
  'Honey Badger',
  'Puffin',
  'Polar Bear',
  'Hyena',
  'Halloween White Ghost Dragon',
  'Lava Dragon',
  'Platypus',
  'Silverback Gorilla',
  'Christmas Pudding Pup',
  'Glacier Kitsune',
  'Aurora Fox',
  'Pineapple Owl',
  'Giant Gold Scarab',
  'Hare',
  'Glacier Moth',
  'Dragonfruit Fox',
  'Alley Cat',
  'Moose Calf',
  'Glormy Leo',
  'Diamond Albatross',
  'Dancing Dragon',
  'Purple Butterfly',
  'Jousting Horse',
  'Dango Penguins',
  'Sushi Penguin',
  'Tree Kangaroo',
  'Ice Cream Hermit Crab',
  'Majestic Pony',
  'Diamond Hummingbird',
  'Arctic Dusk Dragon',
  'Flaming Fox',
  'Rose Dragon',
  'Kookaburra',
  'Llama',
  'Cheetah',
  'Albino Gorilla',
  'Diamond Hamster',
  'Glormy Hound',
  'Slime',
  'Wood Pigeon',
  'Candy Hare',
  'Turkey',
  'Lavender Dragon',
  'Chocolate Dutch Guinea Pig',
  'Latte Kitsune',
  'Husky',
  '2D Kitty',
  'Corn Doggo',
  'Golden Chow-Chow',
  'Lamb',
  'Hero Gibbon',
  'Swan',
  'Golden Penguin',
  'Rainbow Dragon',
  'Silly Duck',
  'Leopard Shark',
  'Queen Bee',
  'Ninja Monkey',
  'Ice Golem',
  'Scorching Kaijunior',
  'Easter 2020 Egg',
  'Leviathan',
  'Diamond King Penguin',
  'Mule',
  'Peahen',
  'Frost Phoenix',
  'Harp Seal',
  'Diamond Ladybug',
  'Skele-Rex',
  'Ice Wolf',
  'Royal Corgi',
  'Chicken',
  'Phoenix',
  'Golden Rat',
  'Shark',
  'Dodo',
  'Astronaut Gorilla',
  'Goldhorn',
  'Chef Gorilla',
  'Apple Owl',
  'Naughty Mistletroll',
  'Prismatic Butterfly',
  'Moonbeam Butterfly',
  'Burger Bear',
  'Snow Monkey',
  'Ram',
  'Peach Owl',
  'Green Butterfly',
  'Vanilla Penguin',
  'Yule Log Dog',
  'Kelp Captain',
  'T-Rex',
  'Pirate Hermit Crab',
  'Spinosaurus',
  'Mini Schnauzer',
  'Lava Wolf',
  'Cerberus',
  'Capybara',
  'Toy Monkey',
  'French Bulldog',
  'Puffer Fish',
  'Unicorn',
  'Rhino',
  'Black Springer Spaniel',
  'Capricorn',
  'Firefly',
  'Shetland Pony Light Brown',
  'Black Panther',
  'Gargoyle',
  'Octopus',
  'Violet Butterfly',
  'Wild Boar',
  'Brown Springer Spaniel',
  'Business Monkey',
  'Volcanic Rhino',
  'Kiwi',
  'White Sand Dollar',
  'Drake',
  'Cactus Friend',
  'Gaelic Fae',
  'Axolotl',
  'Panda',
  'German Shepherd',
  'Golden Walrus',
  'Red Sand Dollar',
  'Peacock',
  'Naga Dragon',
  'English Sheepdog',
  'Binturong',
  'Water Rabbit',
  'Winged Horse',
  'Squid',
  'Ghost Bunny',
  'Wooly Rhino',
  'Evil Rock',
  'Yeti',
  'Guardian Lion',
  'Reindeer',
  'Influencer Gibbon',
  'Cuddly Candle',
  'Gilded Snake',
  'Scarebear',
  'White Amazon',
  'Zombie Wolf',
  'Princess Capuchin Monkey',
  'Hippogriff',
  'Golden Hummingbird',
  'Lynx',
  'Pretty Pony',
  'Mushroom Friend',
  'Orange Butterfly',
  'Moon Rabbit',
  'Green-Chested Pheasant',
  'Ghost Dog',
  'Great Pyrenees',
  'Seabed Creeper',
  'Golden Ladybug',
  'Sunrise Duckling',
  'Snowball Pet',
  'Robo Dog',
  'Karate Gorilla',
  'Blue Betta Fish',
  'Snow Owl',
  'Dimorphodon',
  'Golden Hamster',
  'King Bee',
  'Chameleon',
  'Black Chow-Chow',
  'Black Widow',
  'Golden King Penguin',
  'Royal Capuchin Monkey',
  'Maneki-Neko',
  'Chocolate Chow-Chow',
  'Mecha Meow',
  'Baku',
  'Red Squirrel',
  'Super Saru',
  'Winter Buck',
  'Happy Duckling',
  'Dire Stag',
  'Criosphinx',
  'Golden Albatross',
  'Bunny Swirl',
  'Pupcake',
  'Amami Rabbit',
  'Blue Ringed Octopus',
  'Berry Cool Cube',
  'Frostbite Cub',
  'Ranger Beaver',
  'Hawk',
  'Cobra',
  'Billy Goat',
  'Golden Jaguar',
  'Tarsier',
  'Castle Hermit Crab',
  'Chipmunk',
  'Kitsune',
  'Highland Cow',
  'Giant Blue Scarab',
  'Gecko',
  'Chimera',
  'Glormy Dolphin',
  'Space Whale',
  'Hippo',
  'Scarecrow Crow',
  'Musk Ox',
  'Nautilus',
  'Toasty Red Panda',
  'Flower Power Duckling',
  'Quokka',
  'Tasmanian Devil',
  'Ash Zebra',
  'Lunar Moon Bear',
  'Mr. Whiskerpips',
  'Flaming Zebra',
  'Shadow Dragon Ducky',
  'Cow Calf',
  'Black Macaque',
  'Royal Palace Spaniel',
  'Griffin',
  'Shiver Wolf',
  'Dimension Drifter',
  'Pumpkin Friend',
  'Coconut Friend',
  'Merry Mistletroll',
  'Albino Bat',
  'Vermilion Butterfly',
  'Kitty Bat',
  'Villain Gibbon',
  'Koala',
  'Evil Chick',
  'Emberlight',
  'Pink Betta Fish',
  'Elasmosaurus',
  'Horse',
  'Indian Flying Fox',
  'Eggnog Dog',
  'Frostclaw',
  'Primal Kaijunior',
  'Pudding Cat',
  'Moonlight Moth',
  'Leopard Cat',
  'Kraken',
  'Halloween Evil Dachshund',
  'Ice Moth Dragon',
  'Rosy Maple Moth',
  'Headless Horse',
  'Evil Basilisk',
  'Striped Eggy',
  'Halloween Golden Mummy Cat',
  'Golden Tortoise Beetle',
  'Sunglider',
  'Priceless Shrimp',
  'Irish Elk',
  'Candy Cane Snail',
  'Evil Chickatrice',
  'Koi Carp',
  'Fleur De Ice',
  'Water Moon Bear',
  'Scarecrow Cat',
  'Nightmare Owl',
  'Feesh',
  'Cassowary',
  'Preppy Capuchin Monkey',
  'Ostrich',
  'Longhorn Cow',
  'Lunar Gold Tiger',
  'Halloween White Skeleton Dog',
  'Dracula Parrot',
  'Burning Bunny',
  'Chick',
  'Canadian Goose',
  'Inmate Capuchin Monkey',
  'Frog',
  'St Bernard',
  'Summer Walrus',
  'Sprout Snail',
  'Scarlet Butterfly',
  'Therapy Dog',
  'Glyptodon',
  'Partridge',
  'Seagull',
  'Toy Poodle',
  'Wolf',
  'Rooster',
  'King Penguin',
  'Clownfish',
  'Slimingo',
  'Mirai Moth',
  'Punk Pony',
  'Rice Cake Rabbit',
  'Goldfish',
  'Giant Black Scarab',
  'Puptune',
  'Metal Ox',
  'Fire Mare',
  'Bauble Buddies',
  'Snowball Pug',
  'Kage Crow',
  'Magma Moose',
  'Love Bird',
  'Albatross',
  'Brown-Chested Pheasant',
  'Green Amazon',
  'Tanuki',
  'Komodo Dragon',
  'Skunk',
  'Sloth',
  'Seafoam Butterfly',
  'Angus Bull',
  'Praying Mantis',
  'Hummingbird',
  'Peachick',
  'Sweetheart Rat',
  'Clover Cow',
  'Zodiac Minion Chick',
  'Hamster',
  'Penguin',
  'Prism Snake',
  'Magma Snail',
  'Basilisk',
  'Sasquatch',
  '2021 Uplift Butterfly',
  'Mongoose',
  'Sabertooth',
  'Lobster',
  'Diamond Unicorn',
  'Blossom Snake',
  'Starhopper',
  'Nebula Snake',
  'Salamander',
  'Gingerbread Reindeer',
  'Snow Leopard',
  'Steppe Lion',
  'Singularity Pisces',
  'Ghost Chick',
  'Peregrine Falcon',
  'Glormy Crab',
  'Eggnog Hare',
  'Hydra',
  'Bird of Paradise',
  'Malaysian Tapir',
  'Choco Penguin',
  'Deinonychus',
  'Clementine Owl',
  'Sea Angel',
  'Trapdoor Snail',
  'Momma Moose',
  'Spider Crab',
  'Raccoon',
  'Shetland Pony White',
  'Wyvern',
  'Tan Chow-Chow',
  'Kappakid',
  'Kelp Hunter',
  'Fanghorn Tortoise',
  'Grave Owl',
  'Coyote',
  'Pine Marten',
  'Deathstalker Scorpion',
  'Subzero Scorpion',
  'Wildfire Hawk',
  'Roadrunner',
  'Ornate Horned Frog',
  'Christmas Spirit',
  'Vulture',
  'Dirty Ducky',
  'Firefighter Gibbon',
  'Rock',
  'Possum',
  'Eel',
  'Zombie Chick',
  'Ladybug',
  'Lammergeier',
  'Officer Gibbon',
  'Black Dog',
  'Fire Stallion',
  'Black Kite',
  'Ghostly Cat',
  'Cozy Mistletroll',
  'Quetzalcoatl',
  'Yellow Butterfly',
  'Maine Coon',
  'Emu',
  '2022 Uplift Butterfly',
  'Narwhal',
  'Gingerbread Mouse',
  'Rock Pigeon',
  'Dilophosaurus',
  'Australian Kelpie',
  'Ermine',
  'Seahorse',
  'Black Marlin',
  'Woolly Mammoth',
  'Diamond Dragon',
  'Temple Friend',
  'Bloodhound',
  'Ibex',
  'Snowman',
  'Ankylosaurus',
  'Mecha R4BBIT',
  'Winter Doe',
  'Cold Cube',
  'Singularity Beetle',
  'Robin',
  'Ringmaster Gibbon',
  'Gingerbread Hare',
  'Merhorse',
  'Lunar White Tiger',
  'Nutcracker Squirrel',
  'Indian Leopard',
  'Red Fox',
  'Red Crowned Crane',
  'Cute-A-Cabra',
  'Pterodactyl',
  'Undead Elk',
  'Warthog',
  'Manta Ray',
  'Diamond Griffin',
  'Arctic Hare',
  'Halloween White Mummy Cat',
  'Ice Cube',
  'Golden Unicorn',
  'Liger',
  'Arctic Tern',
  'Monkey',
  'Golden Dragon',
  'Chickatrice',
  'Toxic Kaijunior',
  'Mistletroll',
  'Dracula Fish',
  'Stegosaurus',
  'Frogspawn',
  'Dolphin',
  'Orca',
  'Triceratops',
  'Old King Coal',
  'Oryx',
  'Blue Jay',
  'Chilling Spider',
  'Skelebat',
  'Ibis',
  'Slug',
  'Bee',
  'Scarecrow Horse',
  'Lunar Ox',
  'Thorny Devil',
  'Floral Eggy',
  'Lionfish',
  'Pomeranian',
  'DJ Snooze',
  'Birthday Butterfly 2023',
  'Easter Bunny',
  'Dugong',
  'Marabou Stork',
  'Kelp Raider',
  'Persian Cat',
  'Starmite',
  'Poison Dart Frog',
  'Orange Betta Fish',
  'Kirin',
  'Urchin',
  'Woodpecker',
  'Weevil',
  'Winter Fawn',
  'Golden Griffin',
  'Cockroach',
  'Alicorn',
  'Walrus',
  'Rattlesnake',
  'Dragon',
  'Rodeo Bull',
  'Diamond Mahi Mahi',
  'Halloween Black Mummy Cat',
  'Classic Teapot',
  'Banded Palm Civet',
  'Snowy Mammoth',
  'Tarantula',
  'Kaijunior',
  'Frozen Penguin',
  'Dire Wolf',
  'Mrs. Whiskerpips',
  'Gila Monster',
  'Show Pony',
  'Birthday Butterfly 2024',
  'Yellow-Lipped Sea Krait',
  'Black Moon Bear',
  'Gorilla',
  'Ghost',
  'Sea Skeleton Panda',
  'Shetland Pony Dark Brown',
  'Hermit Crab',
  'Zeopod',
  'Halloween Blue Scorpion',
  'Oakee Wizard',
  'Red Cardinal',
  'Fossa',
  'Hammerhead Shark',
  'Icy Porcupine',
  'Moonpine',
  'Crab',
  'Rat',
  'Dark Choccybunny',
  'Dotted Eggy',
  'Kelp Crewmate',
  'Rhino Beetle',
  'Emperor Shrimp',
  'Scarecrow',
  'Tawny Frogmouth',
  'Ground Sloth',
  'Angelfish',
  'Tasmanian Tiger',
  'Tealwood Monster',
  'Dingo',
  'Wolpertinger',
  'Velociraptor',
  'Mochi Meow',
  'Beluga Whale',
  'Dragonfly',
  'Brachiosaurus',
  'Sea Turtle',
  'Ancient Dragon',
  'Mole',
  'Ghost Wolf',
  'Blue Whale',
  'Capuchin Monkey',
  'Ginger Cat',
  'Mosquito',
  'Armadillo',
  'Purrowl',
  'Wren',
  'Kid Goat',
  'Bali Starling',
  'Turtle Doves',
  'Waffle Wyrm',
  'Bandicoot',
  'Ox',
  'Rainbow Trout',
  'Ehecatl',
  'Badger',
  'Angus Calf',
  'Angler Fish',
  'Gibbon',
  'Bat',
  'Samoyed',
  'Ratatoskr',
  'Amber Butterfly',
  'Toucan',
  'Stingray',
  'Bakeneko',
  'Snorgle',
  'Maleo Bird',
  'Hopbop',
  'Borhyaena Gigantica',
  'Onza',
  'Frankenfeline',
  'Piranha',
  'Sado Mole',
  '2025 Birthday Butterfly',
  'Red Panda',
  'Jumping Spider',
  'Lunar Tiger',
  'Sandfish',
  'Bluebottle Fly',
  'Bullfrog',
  'Starfish',
  'Garden Snake',
  'Island Tarsier',
  'Stygian Owl',
  'Storm Condor',
  'Robot',
  'Pangolin',
  'Black-Footed Ferret',
  'Gumball Caterpillar',
  'River Otter',
  'Chanekeh',
  'Corgi',
  'Blue Butterfly',
  'Water Opossum',
  'Tree Sasquatch',
  'Flying Fish',
  'Swordfish',
  'Rubber Ducky',
  'Bison',
  'Humbug',
  'Grinmoire',
  'Otter',
  'Unicorn Ducky',
  'Glyptodon Ducky',
  'Nurse Shark',
  'Ocelot',
  'Mahi Mahi',
  'Fennec Fox',
  'Zebra',
  'Beaver',
  'Bunny',
  'Buffalo',
  'Aye Aye',
  'Mouse',
  'Oakee Knight',
  'Oakee',
  'Tree Frog',
  'Patchy Bear',
  'Irish Setter',
  'Shih Tzu',
  'Red Panda Ducky',
  'Chocolate Labrador',
  'Clubtail Dragonfly',
  'Ant',
  'Sheepdog Ducky',
  'Pilot Gull',
  'Gecko Ducky',
  'Angus Cow',
  'Snow Cat',
  'Gold Mahi Mahi',
  'Mexican Wolf',
  'Black Rhino',
  'Rabbit',
  'Puma',
  'Kakapo',
  'Galapagos Sea Lion',
  'California Condor',
  'Japanese Snow Fairy',
  'Dog',
  'Camel',
  'Fire Foal',
  'Poodle',
  'Ribbon Seal',
  'Cherub Chipmunk',
  'Magpie',
  'Sneak Weasel',
  'Black Tiger',
  'Orangutan',
  'Cat',
  'Cocoadile',
  'Gummy Guana',
  'Donkey',
  'Abyssinian Cat',
  'Tegu',
  'Parakeet',
  'Jiggly Jerboa',
  'Shiba Inu',
  'Milk Choccybunny',
  'White Choccybunny',
  'Muskrat',
  'Snow Puma',
  'Royal Moon Egg',
  'Royal Desert Egg',
  'Royal Aztec Egg',
  'Danger Egg',
  'Urban Egg',
  'Fossil Egg',
  'Wrapped Doll',
  'Pistachio',
  'Dylan',
  'Christmas Future Egg',
  'River',
  'Fool Egg',
  'Ocean Egg',
  'Mythic Egg',
  'Woodland Egg',
  'Southeast Asia Egg',
  'Diamond Egg',
  'Desert Egg',
  'Japan Egg',
  'Zodiac Minion Egg',
  'Golden Egg',
  'Moon Egg',
  'Garden Egg',
  'Admin Abuse Egg',
  'Aztec Egg',
  'Crystal Egg',
  'Royal Egg',
  'Retired Egg',
  'Endangered Egg',
  'Pet Egg',
  'Basic Egg',
  'Cracked Egg',
];

const PETS_NO_POTIONS = new Set([
  'Safari Egg',
  'Jungle Egg',
  'Farm Egg',
  'Blue Egg',
  'Pink Egg',
  'Christmas Egg',
  'Aussie Egg',
  'Easter 2020 Egg',
  'Royal Moon Egg',
  'Royal Desert Egg',
  'Royal Aztec Egg',
  'Danger Egg',
  'Urban Egg',
  'Fossil Egg',
  'Wrapped Doll',
  'Pistachio',
  'Dylan',
  'Christmas Future Egg',
  'River',
  'Fool Egg',
  'Ocean Egg',
  'Mythic Egg',
  'Woodland Egg',
  'Southeast Asia Egg',
  'Diamond Egg',
  'Desert Egg',
  'Japan Egg',
  'Zodiac Minion Egg',
  'Golden Egg',
  'Moon Egg',
  'Garden Egg',
  'Admin Abuse Egg',
  'Aztec Egg',
  'Crystal Egg',
  'Royal Egg',
  'Retired Egg',
  'Endangered Egg',
  'Pet Egg',
  'Basic Egg',
  'Cracked Egg',
]);

function getPetImage(name) {
  if (PET_IMAGES[name]) return PET_IMAGES[name];
  if (name === 'Tio De Nadal') {
    return 'https://fetch-images.b-cdn.net/images/pets/Ti%C3%B3%20De%20Nadal.png';
  }
  return `https://fetch-images.b-cdn.net/images/pets/${encodeURIComponent(name)}.png`;
}

const pets = PETS_ORDER.map((name) => ({
  name,
  image: getPetImage(name),
}));

const PET_WEAR_IMAGES = {
  'Halloween Black Axe Guitar': 'https://fetch-images.b-cdn.net/images/pets/Guitar.png',
  "Founder's Crown": 'https://fetch-images.b-cdn.net/images/pets/Founders%20Crown.png',
  'Aestus Mane': 'pets/aestus-mane.png',
  'Cherry-On-Top': 'pets/cherry-on-top.png',
  'Copter Hat': 'pets/copter-hat.png',
  'Eco Brown Earth-Wizard Hat': 'pets/eco-brown-earth-wizard-hat.png',
  'Chimney Hat': 'pets/chimney-hat.png',
  'Nest of Eggs': 'pets/nest-of-eggs.png',
  'Sack of Cash': 'pets/sack-of-cash.png',
};

const PET_WEAR_ORDER = [
  'SSBD Sunnies',
  'Strawberry Cupcake Shoes',
  'Strawberry Plushie Rider',
  'Rainbow Maker',
  'Giraffe Backpack',
  'Giraffe Hat',
  'SSBD Beanie',
  'Cherry-On-Top',
  'Halo',
  'Angel Wings',
  '2022 Birthday Party Hat',
  'Magic Girl Wings',
  '2022 Birthday Cake',
  'Unicorn Horn',
  '2022 Birthday Cupcake Shoes',
  'Rain Cloud Hat',
  '2022 Birthday Confetti Cannon',
  '2022 Birthday Party Horn',
  'Dragonfly Fairy Wings',
  'Toaster Hat',
  'Tiny Wings',
  'Ice Cream Cone Hat',
  'Head Chef',
  'Strawberry Shortcake Bat Dragon Backpack',
  'Spring Bunny Hood',
  'Ember Wings',
  'Goth Shoes',
  'Unicorn Backpack',
  'Pancake Stack',
  'Gold Crown',
  'Spring Bunny Nose',
  'Shadow Wings',
  'Propeller Hat',
  'Spring Bunny Feet',
  'Santa Hat',
  'Rain Boots',
  'Sandwich Hat',
  'Pink Cat Ear Headphones',
  'Copter Hat',
  'Sushi Skateboard',
  'Sailor Cap',
  'Clockwork Wings',
  'Bready Necklace',
  'Halloween Black Axe Guitar',
  'Chef Hat',
  'Banana Hat',
  'Icey Aura',
  '2022 Birthday Confetti Drape',
  'Eco Brown Hiking Backpack',
  'Monkey King Crown',
  'Shadow Aura',
  "Jeff's Nametag",
  'Invisible Wings',
  'Chocolate Chip Bat Dragon Backpack',
  'Eco Orange Pumpkin Pie Wings',
  'Pink Heart Glasses',
  'Eco Brown Earth-Wizard Hat',
  '2022 Birthday 5 Badge',
  'Strawberry Hat',
  'Jade Moth Wings',
  'Aviator Hat',
  'Demon Wings',
  'Blue Butterfly Wings',
  'Thinking Hat',
  'Bat Wings',
  'Burger Boots',
  'Cowboy Saddle',
  'Alien Eyes Hat',
  'Dancing Tube Hat',
  'White Designer Backpack',
  'Eco Brown Branch Headphones',
  'Butter Knife',
  'Black Designer Backpack',
  'Back Taco',
  'Chicken Hat',
  'Bat Backpack',
  'Steampunk Clock Hat',
  'Cotton Candy Hat',
  'Ice Cream Heels',
  'Brain Jar',
  'Hero Mask',
  'Music Box Hat',
  'Mule Baskets',
  'Witch Hat',
  'Elf Hat',
  'Firey Aura',
  'Blue Cat Ear Headphones',
  'Pirate Hat',
  'Leprechaun Hat',
  'Energy Aura Feet',
  'Rain Hat',
  'Lunar New Year Shoes',
  'Headband',
  'Flower Monocle',
  'Golden Hair',
  'Fishbowl Hat',
  'Lava Lamp Hat',
  'Dumpling Friend Hat',
  'Waterfall Hat',
  'Golden Walrus Crown',
  'Venus Flytrap Hat',
  'Satellite Spinner',
  'Gold Fairy Crown',
  'Lightbulb Hat',
  'Jetpack',
  'Bewitched Hat',
  'Strawberry Clip',
  'Pink Designer Backpack',
  'Ferris Wheel Hat',
  'Watermelon Backpack',
  'Money Hat',
  'Chimney Hat',
  'Puddleducks Hood',
  'Pink Instant Camera',
  'Strawberry Shortcake Bow',
  "Nature's Crown",
  'Tutu',
  'Halloween White Skull Hat',
  "Mandarin's Hat",
  'Yellow Instant Camera',
  'Ponytail',
  'Science Hat',
  'Summer Straw Hat',
  'Summer Walrus Sunhat',
  'Ghost Kitty Backpack',
  'Rubber Ducks',
  'Duck Floatie',
  'Nest of Eggs',
  'Fishbone Badge',
  'Lunar New Year Collar',
  'Flying Fairy',
  'Police Cap',
  'Sack of Cash',
  'City Hat',
  'Grinder Hat',
  'Kraken Hat',
  'Top Hat',
  'Chick Hat',
  'Volcanic Boots',
  'Volcano Hat',
  'Star Sunglasses',
  'Burger Bun Hat',
  'Personal Controller',
  'Heart Bow',
  'Glamicorn Purse Pet',
  'Llamalush Purse Pet',
  'Chick Backpack',
  'Halloween Evil Barrel Backpack',
  'Buttoned Ushanka',
  'Puppeteer Hand',
  'Pink Butterfly Wings',
  'Halloween Orange Pumpkin Friend Hat',
  'Bunny Ear Tiara',
  'Candy Corn Hat',
  'Heart Hat',
  'Heart Ribbon',
  'Bear Hood',
  'Candy Cane',
  'Bee Hive',
  'Glormy Backpack',
  "Santa's Bow",
  'Heart Lock Necklace',
  'Pink Hightops',
  'Eaten Donut',
  'Aestus Mane',
  'Rotating Periscope',
  'Gold Tiara',
  'Leaf Hat',
  'Mystic Wing Crown',
  'Security Spotlight',
  'Gold Circle Glasses',
  'Knitted Pumpkin Hat',
  'Ghost Hat',
  "Founder's Crown",
  'Marshmallow Friend',
  'Black Hightops',
  'Human Feet Shoes',
  'Festive Stocking Shoes',
  'Festive Scarf',
];

function getPetWearImage(name) {
  if (PET_WEAR_IMAGES[name]) return PET_WEAR_IMAGES[name];
  return getPetImage(name);
}

const petWear = PET_WEAR_ORDER.map((name) => ({
  name,
  image: getPetWearImage(name),
}));

const STROLLERS_ORDER = [
  'Egg Stroller',
  'Quad Stroller',
  'Heart Stroller',
  'Vampire Stroller',
  'Race Car Stroller',
  'Duck Stroller',
  'Cradle Stroller',
  'Bunny Stroller',
  'Baby Basket Stroller',
  'Unicorn Stroller',
  'Half Egg Stroller',
  'Easter Egg Stroller',
  'Floating Hand Stroller',
  'Rainbow Stroller',
  'Ice Cream Stroller',
  'Pizza Stroller',
  'Cauldron Stroller',
  'Web Stroller',
  'French Fries Stroller',
  'Popsicle Stroller',
  'Kangaroo Stroller',
  'Balloon Stroller',
  'Strawberry Stroller',
  'Cannon Stroller',
  'Trike Stroller',
  'Flower Stroller',
  'Pumpkin Stroller',
  'Elephant Stroller',
  'Reindeer Stroller',
  'Red Wagon Stroller',
  'Banana Stroller',
  'Triple Stroller',
];

function getStrollerImage(name) {
  return getPetImage(name);
}

const strollers = STROLLERS_ORDER.map((name) => ({
  name,
  image: getStrollerImage(name),
}));

const FOOD_IMAGES = {
  'Fly-A-Pet Potion': 'pets/fly-a-pet-potion.png',
  'Ride-A-Pet Potion': 'pets/ride-a-pet-potion.png',
  'Broken Egg': 'pets/broken-egg.png',
};

const FOOD_ORDER = [
  'Water Walking Potion',
  'Golden Leaf',
  'Candy Cane',
  'Goldenrod Flower',
  'Snowflake Potion',
  'Dim Sum',
  'Chocolate',
  'Heart Potion',
  'Christmas Pudding Pup Bait',
  'Super Age-Up Potion',
  'Chocolate Egg',
  'Golden Lettuce',
  'Sugar Skull Potion',
  'Teleportation Potion',
  'Chocolate Drop',
  'Levitation Potion',
  'Broken Egg',
  'Leaf',
  'Fly-A-Pet Potion',
  'Chocolate Twist',
  'Baked Alaska Bait',
  'Ice Tub',
  'Golden Dandelion',
  'Golden Seed Ball',
  'Golden Plantain',
  'Golden Corn',
  'Maple Leaf Treat',
  'Golden Petunia',
  'Ride-A-Pet Potion',
  'Golden Goldfish',
  'Golden Wheat',
  'Golden Bone',
  'Golden Clam',
  'Diamond Lavender',
  'Mud Ball',
  'Honey',
  'Cookie',
  'Ash Zebra Bait',
  'Flaming Zebra Bait',
  'Burnt Bites Bait',
  'Stripes Egg',
  'Stars Egg',
  'Patterns Egg',
  'Taco',
  'Subzero Popsicle Bait',
  'Snapdragon Flower',
  'Winter Deer Bait',
  'Shiver Cone Bait',
  'Strawberry Shortcake',
  'Fire Horse Apple',
];

function getFoodImage(name) {
  if (FOOD_IMAGES[name]) return FOOD_IMAGES[name];
  return getPetImage(name);
}

const food = FOOD_ORDER.map((name) => ({
  name,
  image: getFoodImage(name),
}));

const VEHICLE_IMAGES = {
  'Cloud Car': 'pets/cloud-car.webp',
  'Horse And Carriage': 'pets/horse-and-carriage.png',
  'Ketchup and Mustard Jetpack': 'pets/ketchup-and-mustard-jetpack.webp',
  'Wing Trunk Car': 'pets/wing-trunk-car.png',
  'White Neon Snowboard': 'pets/white-neon-snowboard.png',
};

const VEHICLES_ORDER = [
  'Neon Black Scooter',
  'Ghost Vehicle',
  'Cloud Car',
  'Super Jetpack',
  'Rocket Sled',
  'Giant Cheetah Mount',
  'Bunny Carriage',
  'Snow Snowboard',
  'Gold Snowboard',
  'Ice Snowboard',
  'Roblox Snowboard',
  'Blue Neon Snowboard',
  'Pink Neon Snowboard',
  'White Neon Snowboard',
  'Bathtub',
  'GoKart',
  'Horse And Carriage',
  'Green Neon Snowboard',
  'Shooting Star Board',
  'Mono-Moped',
  'Dragon Train',
  'Crescent Moon Car',
  'Glass Snowboard',
  'Neon Black Skateboard',
  'Orange Neon Snowboard',
  'Unicorn Cycle',
  'Flower Truck',
  'Horse Cycle',
  'Adopt Me Snowboard 1',
  'Adopt Me Snowboard 2',
  'Neon White Skateboard',
  'Neon White Scooter',
  'Enchanted Broomstick',
  'Convertible',
  'Neon Orange Skateboard',
  'Neon Green Skateboard',
  'Neon Blue Skateboard',
  'Neon Pink Skateboard',
  'Neon Red Skateboard',
  'Neon Orange Scooter',
  'Toxic Barrel',
  'Black Scooter',
  'Gyrocopter',
  'Hot Tub Muscle Car',
  'Ketchup and Mustard Jetpack',
  'Neon Pink Scooter',
  'Rabbit Helicopter',
  'Neon Green Scooter',
  'Toy Rescue Helicopter',
  'Neon Red Scooter',
  'Neon Blue Scooter',
  'Dogmobile',
  'Flying Cloud',
  'Moped',
  'Monocycle',
  'Cupcake Scooter',
  'Doge Scooter',
  'Adopt Me Girl Scooter',
  'Adopt Me Boy Scooter',
  'Donut Cycle',
  'Pumpkin Carriage',
  'Regal Roller',
  "Cupid's Coupe",
  'Doge Skateboard',
  'Street Drifter',
  'Rose Petal Carriage',
  'Gingerbread Sleigh',
  'Gold Skateboard',
  'Wood Skateboard',
  'Glass Scooter',
  'Bethink Skateboard',
  'Fissy Skateboard',
  'Ice Scooter',
  'Fidget Skateboard',
  'Glass Skateboard',
  'Emoji Scooter',
  'Royal Crown Carriage',
  'Crabby Cruiser',
  'Ice Cream Truck',
  'Snowmobile',
  'Halloween Black Ponycycle',
  'Black Snowboard',
  'White Snowboard',
  'Pink Skateboard',
  'Blue Skateboard',
  'White Skateboard',
  'Black Skateboard',
  'Blue Scooter',
  'Duck Scooter',
  'Ice Plane',
  'Husky Sled',
  'Shadow Rider',
  'Pink Scooter',
  'White Scooter',
  'Wood Scooter',
  "Headless Horseman's Biplane",
  'Festive Deliveries Sleigh',
  'Blue Snowboard',
  'Santa Copter',
  'Daisymobile',
  'Hoverboard',
  'Fossil Paw Helicopter',
  "Emperor's Chariot",
  "Santa's Sleigh",
  'Flower Wagon',
  'Tiffany',
  'Lavender Teapot Carriage',
  'Axel',
  'Wing Trunk Car',
  'Snowblower Toboggan',
  'Royal Carriage',
  'Princess Carriage',
  'Lava Racer',
  'Bubble Car',
  'Prince Carriage',
  'Giant Snowball',
  'Traveling House',
  'Paint Roller Truck',
  'Egg Delivery Machine',
  'Unicorn Zombie Ponycycle',
  'Shadow Dragon Skateboard',
  'Yellow Taxi Cab',
  'Black Cab',
  'Heart Hoverboard',
  'Squirrel Car',
  'Hovertible',
  'Douglas',
  'Ice Queen Sleigh',
  'Ribcage Carriage',
  'Banana Car',
  'Hovercar',
  'Candy Snowmobile',
  'Dragonster',
  'Choo Choo Train',
  'Inspector Sherbet Bus',
  'SUV',
  'Imagination Box',
  'Gummy Biplane',
  'RGB Monster Truck',
  'Micro Car',
  'RGB UFO',
  'Hot Rod Sleigh',
  'Snow Plow',
  'Latte Motorcycle',
  'Dolphin Cruiser',
];

function getVehicleImage(name) {
  if (VEHICLE_IMAGES[name]) return VEHICLE_IMAGES[name];
  return getPetImage(name);
}

const vehicles = VEHICLES_ORDER.map((name) => ({
  name,
  image: getVehicleImage(name),
}));

const TOY_IMAGES = {
  'Campfire Stories Mega Neon Paint': 'pets/campfire-stories-mega-neon-paint.webp',
  'Velvet Fuchsia Mega Neon Paint': 'pets/velvet-fuchsia-mega-neon-paint.png',
  'Stygian Hang Glider': 'pets/stygian-hang-glider.png',
};

const TOYS_ORDER = [
  'Rainbow Rattle',
  'Candy Cannon',
  'Flying Broomstick',
  'Tombstone Ghostify',
  'Pumpkin',
  'Chinese Lantern',
  'Cherry Blossom Hang Glider',
  'Tea Party Set',
  'Teddy Skele',
  'Heart Rattle',
  'Unicorn Plush',
  'Hugging Egg',
  'Tea Party Chair',
  'Wing Hang Glider',
  'Glider',
  'Skeleton Winged Glider',
  'Panda Pal',
  'Sunrise Hang Glider',
  'Pumpkin Rattle',
  'Witches Wand',
  'Hot Cocoa Stand',
  'Cat Plush',
  'Celebration Firework Launcher',
  'Staff Ingredient',
  'Zombie Buffalo Plush',
  'Homeing Rocket',
  'Creator Rattle (Bethink)',
  'Magic House Door',
  'Dance Arcade Stand',
  'Creator Rattle (NewFissy)',
  'Netzooka',
  'Unicorn Leash',
  'Axe Rattle',
  'Snow Cone Stand',
  'Classic Trade Stand',
  'Cotton Candy Stand',
  'Santa Throne',
  'Phoenix Plush',
  'Halloween Slime Mega Neon Paint',
  'Discosplosion',
  'Ice Saber',
  'Candyfloss Mega Neon Paint',
  'Anna Rattle',
  'Frosty Glow Mega Neon Paint',
  'Campfire Stories Mega Neon Paint',
  'Rose Quartz Glow Mega Neon Paint',
  'Tropical Surge Mega Neon Paint',
  'Llama Plush',
  'Bunny Plush',
  'Elephant Plush',
  'Puppy Plush',
  'Chick Plush',
  'Croc Plush',
  'Velvet Fuchsia Mega Neon Paint',
  'Amethyst Skies Mega Neon Paint',
  'Electric Tide Mega Neon Paint',
  'Easter Bunny Plush',
  'Candy Flare Mega Neon Paint',
  'Egg Rattle',
  'Rainbow Wand',
  'Throwing Pumpkin',
  'Christmas Doge Rattle',
  'Christmas Cat Rattle',
  'Marsh Plush',
  'Caticorn Rattle',
  'Reindeer Plush',
  'Polar Bear Plush',
  'Octopus Plush',
  'Money Rattle',
  'Heart Plushie',
  'Heart Balloon',
  'Hotdog Stand',
  'Banana Plush',
  'Turkey Plush',
  'Slimingo Feather Teleporter',
  'Lemonade Stand',
  'Cookie Dough Plush',
  'Strawberry Toast Flying Disc',
  'Sour Glider',
  'Fall Corn Grappling Hook',
  'Stygian Hang Glider',
  'Dragon Balloon',
  'Teddy Bear',
  'Paint Sealer',
];

function getToyImage(name) {
  if (TOY_IMAGES[name]) return TOY_IMAGES[name];
  return getPetImage(name);
}

const toys = TOYS_ORDER.map((name) => ({
  name,
  image: getToyImage(name),
}));

const GIFTS_ORDER = [
  'Premium Monkey Box',
  'Golden Gift',
  'Christmas Gift',
  'Rat Box',
  'Golden Mistletoe',
  'Monkey Box',
  'Premium Gorilla Box',
  'Pet Handler Pro Certificate',
  'Premium Capuchin Box',
  'Premium Gibbon Box',
  'Bat Box',
  '1000 Bucks Silk Bag',
  'Hare Box',
  'Regal Wing Chest',
  'Walrus Box',
  'Duckling Box',
  'Hermit Crab Box',
  'Wolf Box',
  'Pony Box',
  'Scarecrow Box',
  'Special Lunar New Year Gift Box',
  'Easter Eggy Box',
  'Halloween Mummy Cat Box',
  'Moon Bear Box',
  'Halloween Chick Box',
  'Lunar Tiger Box',
  'Standard Capuchin Box',
  'Ox Box',
  'Standard Gorilla Box',
  'Standard Gibbon Box',
  '2D Box',
  'Admin Abuse Box',
];

function getGiftImage(name) {
  return getPetImage(name);
}

const gifts = GIFTS_ORDER.map((name) => ({
  name,
  image: getGiftImage(name),
}));

const STICKER_IMAGES = {
  'Solaris Animated Sticker': 'pets/solaris-animated-sticker.webp',
};

const STICKERS_ORDER = [
  'Bat Dragon Cuddle Animated Sticker',
  'Spinning Cat Animated Sticker',
  'Seagull Yell Animated Sticker',
  'Blazing Lion Animated Sticker',
  'Jekyll Hydra Animated Sticker',
  'Dragon Breath Animated Sticker',
  'Super Saru Animated Sticker',
  'Frostclaw Animated Sticker',
  'Mermicorn Animated Sticker',
  'Pets Plus Sticker Pack',
  'Shadow Dragon Animated Sticker',
  'Solaris Animated Sticker',
  'Vol. 2 Pets Plus Sticker Pack',
  'Tree Decorating Animated Sticker',
  'Mochi Meow Tumble Animated Sticker',
  'Strawberry Shortcake Bat Dragon Sticker',
  'Premium Sticker Pack',
  'Pretty Please Snowball Sticker',
  'Bat Dragon Sticker',
  'Frostbite Bear and Cub Animated Sticker',
  'Round Fallow Deer Sticker',
  'Long Ermine Sticker',
  'Wailing Mr. Whiskerpips Sticker',
  'Well, Actually Walrus Sticker',
  'Winter Deer Family Sticker',
  'Cow Loves This Sticker',
  'Balloon Unicorn Sticker',
  'Wet Owl Sticker',
  'Hamster Selfie Sticker',
  'Dinner Discourse Cat Sticker',
  'Parrot Sticker',
  'Winged Horse Sticker',
  'Space Whale Sticker',
  'Phoenix Sticker',
  'Kitsune Sticker',
  'Squished Red Pandorama Sticker',
  'African Painted Dog Sticker',
  'Turtle Sticker',
  'Flamingo Sticker',
  'Pelican Sticker',
  'Dalmatian Sticker',
  'Shark Puppy Sticker',
  'Hot Doggo Sticker',
  'Fairy Bat Dragon Sticker',
  'Elephant Sticker',
  'Cow Sticker',
  'Peppermint Penguin Sticker',
  'Panda Sticker',
  'Orange Butterfly Sticker',
  'Mini Pig Sticker',
  'Fox Sticker',
  'Poodle Sticker',
  'Sasquatch Sticker',
  'Pig Sticker',
  'Pet Rock Sticker',
  'Koala Sticker',
  'Halloween 2024 Sticker Pack',
  'Winter 2024 Sticker Pack',
  'Ginger Cat Sticker',
  'Candyfloss Chick Sticker',
  'Frog Sticker',
  'Walrus Sticker',
  'Shiba Inu Sticker',
  'Rat Sticker',
  'Otter Sticker',
  'State Fair Sticker Pack',
  'Fire Dimension Sticker Pack',
  'Fossil Sticker Pack',
  'Cherry Blossom Flower Sticker',
  'Cherry Blossom Tree Sticker',
];

function getStickerImage(name) {
  if (STICKER_IMAGES[name]) return STICKER_IMAGES[name];
  return getPetImage(name);
}

const stickers = STICKERS_ORDER.map((name) => ({
  name,
  image: getStickerImage(name),
}));

const HOUSE_IMAGES = {
  "Ruler's Castle": 'https://amvgg.com/items/Rulers%20Castle.webp',
  "Dragon's Castle": 'https://amvgg.com/items/Dragons%20Castle.webp',
};

const HOUSES_ORDER = [
  'Cozy Cabin',
  'Eco Natural Earth House',
  'Toyshop House',
  'Space Fleet House',
  'Expandable Dino House',
  'Millionaire Mansion',
  'Mermaid Mansion',
  'Celebrity Mansion',
  'Biodome Home',
  "Ruler's Castle",
  'Expandable Luxury Mansion',
  'Schoolhouse Home',
  'Hospital Home',
  'Modern Mansion',
  'Soccer Stadium',
  'Halloween Hotel',
  'Luxury Apartments',
  'Pirate Ship House',
  'Hollywood House',
  'Party House',
  'Mountain House',
  "Dragon's Castle",
  'Igloo Home',
  'Scary House',
  'Royal Palace',
  'Mansion',
  'Futuristic House',
  'Christmas Pudding House',
  'Sandbox Island',
  'Safari Home',
  'Racetrack House',
  'Crooked House',
  'Lunar House',
  'Haunted House',
];

function getHouseImage(name) {
  if (HOUSE_IMAGES[name]) return HOUSE_IMAGES[name];
  return `https://amvgg.com/items/${encodeURIComponent(name)}.webp`;
}

const houses = HOUSES_ORDER.map((name) => ({
  name,
  image: getHouseImage(name),
}));

const SIGN_IMAGES = {
  Adds: 'pets/adds.png',
};

function getSignImage(name) {
  if (SIGN_IMAGES[name]) return SIGN_IMAGES[name];
  const label = name.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const fontSize = name.length > 12 ? 11 : name.length > 8 ? 13 : 15;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><rect width="128" height="128" rx="14" fill="#1f2937"/><rect x="8" y="8" width="112" height="112" rx="10" fill="#374151"/><text x="64" y="66" text-anchor="middle" dominant-baseline="middle" fill="#ffffff" font-family="Outfit,Arial,sans-serif" font-size="${fontSize}" font-weight="700">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const SIGNS_ORDER = ['Adds'];

const signs = SIGNS_ORDER.map((name) => ({
  name,
  image: getSignImage(name),
}));

function normalizeSearchText(text) {
  return text
    .toLowerCase()
    .replace(/[.\-'_]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function compactSearchText(text) {
  return normalizeSearchText(text).replace(/\s/g, '');
}

function getNameAcronym(name) {
  return name
    .split(/[\s.\-'_]+/)
    .filter(Boolean)
    .map((word) => word[0]?.toLowerCase() ?? '')
    .join('');
}

function matchesSearchQuery(name, query) {
  const normalizedQuery = query.trim().toLowerCase();
  if (!normalizedQuery) return true;

  const lowerName = name.toLowerCase();
  if (lowerName.includes(normalizedQuery)) return true;

  const normalizedName = normalizeSearchText(name);
  const normalizedQuerySpaced = normalizeSearchText(query);
  if (normalizedQuerySpaced && normalizedName.includes(normalizedQuerySpaced)) return true;

  const compactName = compactSearchText(name);
  const compactQuery = compactSearchText(query);
  if (compactQuery && compactName.includes(compactQuery)) return true;

  if (/^[a-z0-9]+$/i.test(normalizedQuery)) {
    return getNameAcronym(name).startsWith(normalizedQuery);
  }

  return false;
}
